const AUTH_ROUTES_SEGMENTS = {
  AUTH: 'auth',
  LOGIN: 'login',
  REGISTER: 'register',
  FORGOT_PASSWORD: 'forgot-password',
  UPDATE_PASSWORD: 'update-password',
};

const AUTH_ROUTES = {
  AUTH: `/${AUTH_ROUTES_SEGMENTS.AUTH}`,
  LOGIN: `/${AUTH_ROUTES_SEGMENTS.AUTH}/${AUTH_ROUTES_SEGMENTS.LOGIN}`,
  REGISTER: `/${AUTH_ROUTES_SEGMENTS.AUTH}/${AUTH_ROUTES_SEGMENTS.REGISTER}`,
  FORGOT_PASSWORD: `/${AUTH_ROUTES_SEGMENTS.AUTH}/${AUTH_ROUTES_SEGMENTS.FORGOT_PASSWORD}`,
  UPDATE_PASSWORD: `/${AUTH_ROUTES_SEGMENTS.AUTH}/${AUTH_ROUTES_SEGMENTS.UPDATE_PASSWORD}`,
} as const;

export { AUTH_ROUTES_SEGMENTS, AUTH_ROUTES };
